server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-321bce68acd3439985428b6202f8f766
      model-name: deepseek-v3
#      api-key: sk-rhpWsFiunpG1oKjy3a8e55760477442b8f0688Db9b0715C2
#      model-name: gpt-3.5-turbo
      log-requests: true
      log-responses: true
#      base-url: https://api.xty.app/v1/
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      log-requests: true
      log-responses: true
      timeout: PT60S
      temperature: 0.8
  community:
    dashscope:
      chat-model:
        api-key: sk-321bce68acd3439985428b6202f8f766
        model-name: qwen-max
# mongoDB连接配置
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: chat_memory_db
      authentication-database: admin
      username: mongo
      password: mongo
# MySQL连接配置
# 基本数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guiguxiaozhi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 开启 SQL 日志打印
mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: debug
